apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthpod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthapp
  template:
    metadata:
      labels:
        app: healthapp
    spec:
      containers:
      - name: c01
        image: tharunselvarangam/healthcaresg
        
---
apiVersion: v1
kind: Service
metadata:
  name: healthservice
spec:
  selector:
    app: healthapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8555
      targetPort: 8082
      nodePort: 30000 # Choose a port number within the range 30000-32767

