apiVersion: v1
kind: Service
metadata:
  name: healthservice
spec:
  selector:
    app: healthapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8555
      targetPort: 8555
      nodePort: 30000 # Choose a port number within the range 30000-32767
